pr: none

jobs:
- job: Linux
  timeoutInMinutes: 600
  pool: 'edtest'
  steps:
  - template: .azure-pipelines/steps/run.yml
  strategy:
    matrix:
      x86_64-gnu-llvm-6.0:
        IMAGE: x86_64-gnu-llvm-6.0
        RUST_BACKTRACE: 1
      dist-86_64-linux:
        IMAGE: dist-x86_64-linux
- job: Windows
  timeoutInMinutes: 600
  pool: 'wintest'
  steps:
  - template: .azure-pipelines/steps/run.yml
  strategy:
    matrix:
      x86_64-msvc-1:
        MSYS_BITS: 64
        RUST_CONFIGURE_ARGS: --build=x86_64-pc-windows-msvc --enable-profiler
        SCRIPT: make ci-subset-1
        NO_DEBUG_ASSERTIONS: 1
        NO_LLVM_ASSERTIONS: 1
