pr: none

jobs:
- job: Linux
  timeoutInMinutes: 600
  pool: 'edtest'
  steps:
  - template: .azure-pipelines/steps/run.yml
  strategy:
    matrix:
      x86_64-gnu-llvm-6.0:
        IMAGE: x86_64-gnu-llvm-6.0
        RUST_BACKTRACE: 1
      dist-86_64-linux:
        IMAGE: dist-x86_64-linux

